/**
 * Central registry of error codes used by the API.
 * Keep these stable: clients/tests rely on them.
 */
module.exports = {
  // Generic
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // Auth
  EMAIL_EXISTS: "EMAIL_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  // Password reset
  RESET_TOKEN_INVALID: "RESET_TOKEN_INVALID",

  // Social auth
  TOKEN_REQUIRED: "TOKEN_REQUIRED",
  SOCIAL_TOKEN_INVALID: "SOCIAL_TOKEN_INVALID",
  SOCIAL_AUTH_FAILED: "SOCIAL_AUTH_FAILED",
  SOCIAL_EMAIL_REQUIRED: "SOCIAL_EMAIL_REQUIRED",
  SOCIAL_EMAIL_NOT_VERIFIED: "SOCIAL_EMAIL_NOT_VERIFIED",
};